/**
 * Renders the <head> metadata block for a route.
 *
 * Used in two places, which is the whole point of it living here:
 *   • scripts/generate-seo.mjs  — writes the home-page block into index.html
 *     before every build, so the checked-in file can never drift from config.
 *   • scripts/postbuild.mjs     — writes the /quote block into a prerendered
 *     dist/quote/index.html, so crawlers that don't run JavaScript still get
 *     real per-page metadata.
 *
 * Everything derives from src/config/site.js. Change the domain there and
 * canonicals, Open Graph URLs, the sitemap and robots.txt all follow.
 */

import { absolute, business, graphForRoute } from '../src/config/site.js'

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

export const MARKER_START = '<!-- seo:start — generated by scripts/generate-seo.mjs, do not edit by hand -->'
export const MARKER_END = '<!-- seo:end -->'

export function renderHead(route) {
  const canonical = absolute(route.path)
  const ogImage = absolute(route.ogImage)
  const jsonLd = JSON.stringify(graphForRoute(route))

  return `${MARKER_START}
    <title>${esc(route.title)}</title>
    <meta name="description" content="${esc(route.description)}" />
    <meta name="keywords" content="${esc(route.keywords.join(', '))}" />
    <link rel="canonical" href="${canonical}" />

    <meta name="robots" content="${route.noindex ? 'noindex, follow' : 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'}" />
    <meta name="googlebot" content="${route.noindex ? 'noindex, follow' : 'index, follow, max-image-preview:large'}" />
    <meta name="author" content="${esc(business.name)}" />
    <meta name="geo.region" content="IN-TN" />
    <meta name="geo.placename" content="Tiruchirappalli" />
    <meta name="geo.position" content="${business.geo.latitude};${business.geo.longitude}" />
    <meta name="ICBM" content="${business.geo.latitude}, ${business.geo.longitude}" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${esc(business.name)}" />
    <meta property="og:locale" content="en_IN" />
    <meta property="og:url" content="${canonical}" />
    <meta property="og:title" content="${esc(route.title)}" />
    <meta property="og:description" content="${esc(route.description)}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:alt" content="${esc(route.ogImageAlt)}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="675" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${esc(route.title)}" />
    <meta name="twitter:description" content="${esc(route.description)}" />
    <meta name="twitter:image" content="${ogImage}" />
    <meta name="twitter:image:alt" content="${esc(route.ogImageAlt)}" />

    <script type="application/ld+json">${jsonLd}</script>
    ${MARKER_END}`
}

/** Swaps the marked block in an HTML string for a different route's block. */
export function replaceHead(html, route) {
  const start = html.indexOf(MARKER_START)
  const end = html.indexOf(MARKER_END)
  if (start === -1 || end === -1) {
    throw new Error('SEO markers not found in HTML — has index.html been edited?')
  }
  return html.slice(0, start) + renderHead(route) + html.slice(end + MARKER_END.length)
}
